
        [system]
        config = "config.exyz"
        temperature = 1.2183
        density = 0.6500000000000001
        list_type = "LinkedList"

        [model]
        [model."1-1"]
        name = "LennardJones"
        epsilon = 1.00
        sigma = 1.00
        rcut = 4.00
        shift_potential = false

        [model."1-2"]
        name = "LennardJones"
        epsilon = 1.1523
        sigma = 1.0339
        rcut = 4.00
        shift_potential = false

        [model."2-2"]
        name = "LennardJones"
        epsilon = 1.3702
        sigma = 1.064
        rcut = 4.00
        shift_potential = false

        [simulation]
        type = "Metropolis"
        steps = 1000
        seed = 42
        parallel = false
        output_path = "./"

        [[simulation.move]]
        action = "Displacement"
        probability = 0.9
        policy = "SimpleGaussian"
        parameters = {sigma = 0.05}

        [[simulation.move]]
        action = "DiscreteSwap"
        probability = 0.1
        policy = "DoubleUniform"
        parameters = {species = [1, 2]}

        [[simulation.output]]
        algorithm = "StoreCallbacks"
        callbacks = ["energy"]
        scheduler_params = {linear_interval = 100}

        [[simulation.output]]
        algorithm = "StoreAcceptance"
        dependencies = ["Metropolis"]
        scheduler_params = {linear_interval = 100}

        [[simulation.output]]
        algorithm = "StoreLastFrames"
        scheduler_params = {linear_interval = 1000}
        fmt = "EXYZ"

        