name: CI

on:  
  push:  
    branches: [main, master]  
  pull_request:  

permissions:
  actions: write  
  contents: read  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  
      uses: actions/checkout@v4  

    - name: Set up Julia  
      uses: julia-actions/setup-julia@v2  

    - name: Cache Julia packages  
      uses: julia-actions/cache@v2  

    - name: Build package  
      uses: julia-actions/julia-buildpkg@v1  

    - name: Run tests with coverage  
      uses: julia-actions/julia-runtest@v1  
      with:
        coverage: true  

    - name: Process coverage  
      uses: julia-actions/julia-processcoverage@v1  

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v5  
      with:  
        fail_ci_if_error: true  
        token: ${{ secrets.CODECOV_TOKEN }}  